### ISSUE TITLE
MS support broken

### ISSUE THREAD

**Issue by telegraphic** [ska-sci-ops/aavs_uv#44]
Not sure how this happened ...

```python
17:09:06.8 | INFO | aavs_uv 1.0.0
17:09:06.8 | INFO | Telescope name: aavs2
17:09:06.8 | INFO | Input path:       ../example-data/aavs2_2x500ms/correlation_burst_204_20230927_35116_0.hdf5
17:09:06.8 | INFO | Array config:     /Users/daniel.price/Data/aavs_uv/src/aavs_uv/config/aavs2/uv_config.yaml
17:09:06.8 | INFO | Output path:      test.ms
17:09:06.8 | INFO | Output format:    ms

17:09:06.8 | INFO | Conjugating data: True

Traceback (most recent call last):
  File "/Users/daniel.price/Data/aavs_uv/tests/test_converter.py", line 148, in <module>
    test_converter()
  File "/Users/daniel.price/Data/aavs_uv/tests/test_converter.py", line 24, in test_converter
    run(cmd)
  File "/Users/daniel.price/Data/aavs_uv/src/aavs_uv/converter.py", line 287, in run
    convert_file(args, fn_in, fn_out, array_config, output_format, conj, context)
  File "/Users/daniel.price/Data/aavs_uv/src/aavs_uv/converter.py", line 146, in convert_file
    writer(fn_out)
  File "/Users/daniel.price/local/mamba/envs/aa3/lib/python3.11/site-packages/pyuvdata/uvdata/uvdata.py", line 12804, in write_ms
    ms_obj.write_ms(
  File "/Users/daniel.price/local/mamba/envs/aa3/lib/python3.11/site-packages/pyuvdata/uvdata/ms.py", line 1219, in write_ms
    ms.putcol(col, temp_vals)
  File "/Users/daniel.price/local/mamba/envs/aa3/lib/python3.11/site-packages/casacore/tables/table.py", line 1155, in putcol
    self._putcol(columnname, startrow, nrow, rowincr, value)
RuntimeError: ArrayColumn::putColumn - column DATA has 65792, array has 4 rows: Table array conformance error
libc++abi: terminating due to uncaught exception of type casacore::AipsError: RegularFile: /Users/daniel.price/Data/aavs_uv/tests/test.ms/table.dat_tmp does not exist and cannot be created
Abort trap: 6
```

**Comment by telegraphic** [comment]
Update: this seems to be due to pyuvdata, not aavs_uv

**Comment by telegraphic** [comment]
Upstream issue: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/issues/1379

Closing here as it needs to be fixed upstream
